# Generated by Django 6.0.2 on 2026-08-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_favorito'),
        ('temas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='TemaEnem',
        ),
        migrations.AlterField(
            model_name='obra',
            name='temas',
            field=models.ManyToManyField(related_name='obras', to='temas.temaenem'),
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
        migrations.DeleteModel(
            name='Favorito',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
