# Generated by Django 6.0.2 on 2026-08-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorito', models.BooleanField(default=False)),
                ('lido', models.BooleanField(default=False)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_interagiram', to='obras.obra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_obras', to='usuarios.usuario')),
            ],
        ),
    ]
