# Generated by Django 6.0.3 on 2026-09-29 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_capa_url_links_externos'),
        ('usuario_obra', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioobra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_obras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usuarioobra',
            constraint=models.UniqueConstraint(fields=('usuario', 'obra'), name='usuario_obra_unica_por_conta'),
        ),
    ]
